### ISSUE TITLE
Maybe remove the httprouter dependency?

### ISSUE THREAD

**Issue by peterhellberg** [dstotijn/ct-diag-server#16]
The [README](https://github.com/dstotijn/ct-diag-server#goals) states:

> Security: rely on Go's standard library where possible, minimal usage of vendor dependencies.

And it seems to me that `net/http` would work well for this project instead of relying on the third party `httprouter` package.

@dstotijn What do you think about removing the `httprouter` dependency? 
(If you agree then I’d be happy to open a PR, just wanted to ask first)

**Comment by dstotijn** [comment]
Yes, I agree. Please feel free to open a PR. Thanks!
