### ISSUE TITLE
Data deletion after 14 days

### ISSUE THREAD

**Issue by arianvp** [dstotijn/ct-diag-server#24]
It is also important to come up with a mechanism to invalidate any upstream caches / CDNs that are caching the tracing keys

**Comment by dstotijn** [comment]
Related: #20

**Comment by dstotijn** [comment]
Proposed solution:
* Add `created_at` column to `diagnosis_keys` table, with timestamp of upload.
* Cleanup after `n` (14?) days, either as part of the running server, or by at least providing a `.sql` file that server operators can use for manual scheduling.
