### ISSUE TITLE
Add TLS support for the server

### ISSUE THREAD

**Issue by arianvp** [dstotijn/ct-diag-server#25]
It's only a few extra lines of go.

Even if this is not the app that will directly be serving the traffic; having mutual TLS authentication between all components `cache <-> proxy <-> ct-diag-server <-> database` is good practice.

Would also like to configure TLS verification for the postgres connection if possible.

**Comment by dstotijn** [comment]
TLS verification for postgres connections is already possible by supplying a DSN with `sslmode=verify-full` ([ref](https://github.com/lib/pq/blob/0ac245bc3be505fde6900e1ca0f957c0845cbfa2/ssl.go)).

**Comment by dstotijn** [comment]
Given the target use case of this server (large scale, horizontally distributed) I reckon TLS should be configured upstream in the hosting infra by the server operator, e.g. somewhere in a GCP loadbalancer, AWS CloudFront, HAProxy, nginx, etc.
